# Generated by Django 4.0 on 2021-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SunTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('solar_noon', models.TimeField()),
                ('day_length', models.TimeField()),
                ('civil_twilight_start', models.TimeField()),
                ('civil_twilight_end', models.TimeField()),
                ('nautical_twilight_start', models.TimeField()),
                ('nautical_twilight_end', models.TimeField()),
                ('astronomical_twilight_start', models.TimeField()),
                ('astronomical_twilight_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_transition', models.IntegerField()),
                ('off_transition', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('morning', models.TimeField()),
                ('evening', models.TimeField()),
                ('ping_bulb_freq', models.IntegerField()),
            ],
        ),
    ]
